// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	"github.com/thumbrise/autosolve/cmd"
	"github.com/thumbrise/autosolve/cmd/cmds"
	"github.com/thumbrise/autosolve/internal/application"
	"github.com/thumbrise/autosolve/internal/application/issue"
	"github.com/thumbrise/autosolve/internal/bootstrap"
	"github.com/thumbrise/autosolve/internal/infrastructure/config"
	"github.com/thumbrise/autosolve/internal/infrastructure/logger"
)

// Injectors from wire.go:

func InitializeContainer(ctx context.Context) (*bootstrap.Container, error) {
	kernel := bootstrap.NewKernel()
	slogLogger := logger.NewSlogLogger()
	validator := config.NewValidator()
	viper := config.NewViper(slogLogger)
	reader := config.NewReader(slogLogger, validator, viper)
	worker := issue.NewWorker(reader)
	scheduler := application.NewScheduler(worker)
	schedule := cmds.NewSchedule(kernel, scheduler)
	v := cmd.Commands(schedule)
	loader := config.NewLoader(slogLogger, viper)
	loggerLoader := logger.NewLoader()
	container := bootstrap.NewContainer(v, loader, kernel, loggerLoader)
	return container, nil
}
