name: "autosolve"

services:
  hyperdx:
    image: docker.hyperdx.io/hyperdx/hyperdx-local:2-beta
    ports:
      - "8080:8080"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - hyperdx-data:/var/lib/clickhouse
    restart: unless-stopped

volumes:
  hyperdx-data: