// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"context"
	"github.com/thumbrise/autosolve/cmd"
	"github.com/thumbrise/autosolve/cmd/cmds"
	"github.com/thumbrise/autosolve/internal/application"
	config2 "github.com/thumbrise/autosolve/internal/config"
	"github.com/thumbrise/autosolve/internal/domain/spec/preflights"
	"github.com/thumbrise/autosolve/internal/domain/spec/workers"
	"github.com/thumbrise/autosolve/internal/infrastructure/config"
	"github.com/thumbrise/autosolve/internal/infrastructure/dal/repositories"
	"github.com/thumbrise/autosolve/internal/infrastructure/dal/sqlcgen"
	"github.com/thumbrise/autosolve/internal/infrastructure/database"
	"github.com/thumbrise/autosolve/internal/infrastructure/github"
	"log/slog"
)

// Injectors from wire.go:

func InitializeKernel(contextContext context.Context, reader *config.Reader, log *config2.Log, logger *slog.Logger) (*Kernel, error) {
	configGithub, err := config2.NewGithub(contextContext, reader)
	if err != nil {
		return nil, err
	}
	rateLimiter := github.NewRateLimiter(configGithub)
	client := github.NewGithubClient(configGithub, rateLimiter)
	githubClient := github.NewClient(client, logger)
	configDatabase, err := config2.NewDatabase(contextContext, reader)
	if err != nil {
		return nil, err
	}
	db, err := database.NewDB(contextContext, configDatabase)
	if err != nil {
		return nil, err
	}
	queries := sqlcgen.New()
	repositoryRepository := repositories.NewRepositoryRepository(db, queries, logger)
	repositoryValidator := preflights.NewRepositoryValidator(githubClient, repositoryRepository, logger)
	v := application.NewPreflights(repositoryValidator)
	issueRepository := repositories.NewIssueRepository(db, queries, logger)
	issuePoller := workers.NewIssuePoller(configGithub, githubClient, issueRepository, logger)
	v2 := application.NewWorkers(issuePoller)
	planner := application.NewPlanner(configGithub, v, v2, repositoryRepository)
	scheduler := application.NewScheduler(planner, logger)
	schedule := cmds.NewSchedule(scheduler)
	migrate := cmds.NewMigrate()
	migrator, err := database.NewMigrator(db)
	if err != nil {
		return nil, err
	}
	migrateUp := cmds.NewMigrateUp(migrator, logger)
	migrateUpFresh := cmds.NewMigrateUpFresh(migrator, logger)
	migrateDown := cmds.NewMigrateDown(migrator, logger)
	migrateStatus := cmds.NewMigrateStatus(migrator)
	migrateCreate := cmds.NewMigrateCreate(migrator)
	migrateRedo := cmds.NewMigrateRedo(migrator, logger)
	test := cmds.NewTest(logger)
	testSubTree := cmds.NewTestSubTree(logger)
	v3 := cmd.NewCommands(schedule, migrate, migrateUp, migrateUpFresh, migrateDown, migrateStatus, migrateCreate, migrateRedo, test, testSubTree)
	root := cmd.NewRoot()
	kernel := NewKernel(v3, db, logger, root)
	return kernel, nil
}
