// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"context"
	"github.com/thumbrise/autosolve/cmd"
	"github.com/thumbrise/autosolve/cmd/cmds"
	"github.com/thumbrise/autosolve/internal/application"
	"github.com/thumbrise/autosolve/internal/application/issue"
	config2 "github.com/thumbrise/autosolve/internal/config"
	"github.com/thumbrise/autosolve/internal/infrastructure/config"
	"github.com/thumbrise/autosolve/internal/infrastructure/dal"
	"github.com/thumbrise/autosolve/internal/infrastructure/dal/repositories"
	"github.com/thumbrise/autosolve/internal/infrastructure/database"
	"github.com/thumbrise/autosolve/internal/infrastructure/github"
	"github.com/thumbrise/autosolve/internal/infrastructure/telemetry"
	"log/slog"
)

// Injectors from wire.go:

func InitializeKernel(contextContext context.Context, reader *config.Reader, log *config2.Log, logger *slog.Logger, telemetryTelemetry *telemetry.Telemetry) (*Kernel, error) {
	configGithub, err := config2.NewGithub(contextContext, reader)
	if err != nil {
		return nil, err
	}
	client := github.NewGithubClient(contextContext, configGithub)
	configDatabase, err := config2.NewDatabase(contextContext, reader)
	if err != nil {
		return nil, err
	}
	db, err := database.NewGormDB(logger, configDatabase, log)
	if err != nil {
		return nil, err
	}
	issueRepository := repositories.NewIssueRepository(db, logger)
	parser := issue.NewParser(configGithub, client, issueRepository, logger)
	worker := issue.NewWorker(configGithub, logger, parser)
	scheduler := application.NewScheduler(worker, logger)
	schedule := cmds.NewSchedule(scheduler)
	test := cmds.NewTest(logger)
	testSubTree := cmds.NewTestSubTree(logger)
	v := cmd.NewCommands(schedule, test, testSubTree)
	v2 := _wireValue
	migrator := database.NewMigrator(db, logger, v2)
	root := cmd.NewRoot()
	kernel := NewKernel(v, logger, migrator, root, telemetryTelemetry)
	return kernel, nil
}

var (
	_wireValue = dal.Models
)
