// Copyright 2026 thumbrise
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issues.sql

package sqlcgen

import (
	"context"
	"time"
)

const getLastUpdateTime = `-- name: GetLastUpdateTime :one
SELECT github_id, github_updated_at
FROM issues
ORDER BY github_updated_at DESC
LIMIT 1
`

type GetLastUpdateTimeRow struct {
	GithubID        int64
	GithubUpdatedAt time.Time
}

func (q *Queries) GetLastUpdateTime(ctx context.Context, db DBTX) (GetLastUpdateTimeRow, error) {
	row := db.QueryRowContext(ctx, getLastUpdateTime)
	var i GetLastUpdateTimeRow
	err := row.Scan(&i.GithubID, &i.GithubUpdatedAt)
	return i, err
}

const upsertIssue = `-- name: UpsertIssue :exec
INSERT INTO issues (repository_id, github_id, number, title, body, state,
                    is_pull_request, pr_url, pr_html_url, pr_diff_url, pr_patch_url,
                    github_created_at, github_updated_at, synced_at)
VALUES (?, ?, ?, ?, ?, ?,
        ?, ?, ?, ?, ?,
        ?, ?, ?)
ON CONFLICT(github_id) DO UPDATE SET title             = excluded.title,
                                     body              = excluded.body,
                                     state             = excluded.state,
                                     is_pull_request   = excluded.is_pull_request,
                                     pr_url            = excluded.pr_url,
                                     pr_html_url       = excluded.pr_html_url,
                                     pr_diff_url       = excluded.pr_diff_url,
                                     pr_patch_url      = excluded.pr_patch_url,
                                     github_created_at = excluded.github_created_at,
                                     github_updated_at = excluded.github_updated_at,
                                     updated_at        = datetime('now'),
                                     synced_at         = excluded.synced_at
`

type UpsertIssueParams struct {
	RepositoryID    int64
	GithubID        int64
	Number          int64
	Title           string
	Body            string
	State           string
	IsPullRequest   bool
	PrUrl           *string
	PrHtmlUrl       *string
	PrDiffUrl       *string
	PrPatchUrl      *string
	GithubCreatedAt time.Time
	GithubUpdatedAt time.Time
	SyncedAt        time.Time
}

func (q *Queries) UpsertIssue(ctx context.Context, db DBTX, arg UpsertIssueParams) error {
	_, err := db.ExecContext(ctx, upsertIssue,
		arg.RepositoryID,
		arg.GithubID,
		arg.Number,
		arg.Title,
		arg.Body,
		arg.State,
		arg.IsPullRequest,
		arg.PrUrl,
		arg.PrHtmlUrl,
		arg.PrDiffUrl,
		arg.PrPatchUrl,
		arg.GithubCreatedAt,
		arg.GithubUpdatedAt,
		arg.SyncedAt,
	)
	return err
}
