// Copyright 2026 thumbrise
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issues.sql

package sqlcgen

import (
	"context"
	"time"
)

const getIssueByID = `-- name: GetIssueByID :one
SELECT id, number, title, body, state
FROM issues
WHERE id = ?
`

type GetIssueByIDRow struct {
	ID     int64
	Number int64
	Title  string
	Body   string
	State  string
}

func (q *Queries) GetIssueByID(ctx context.Context, db DBTX, id int64) (GetIssueByIDRow, error) {
	row := db.QueryRowContext(ctx, getIssueByID, id)
	var i GetIssueByIDRow
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Title,
		&i.Body,
		&i.State,
	)
	return i, err
}

const getIssueByRepoAndNumber = `-- name: GetIssueByRepoAndNumber :one
SELECT id, number, title, body, state
FROM issues
WHERE repository_id = ? AND number = ?
`

type GetIssueByRepoAndNumberParams struct {
	RepositoryID int64
	Number       int64
}

type GetIssueByRepoAndNumberRow struct {
	ID     int64
	Number int64
	Title  string
	Body   string
	State  string
}

func (q *Queries) GetIssueByRepoAndNumber(ctx context.Context, db DBTX, arg GetIssueByRepoAndNumberParams) (GetIssueByRepoAndNumberRow, error) {
	row := db.QueryRowContext(ctx, getIssueByRepoAndNumber, arg.RepositoryID, arg.Number)
	var i GetIssueByRepoAndNumberRow
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Title,
		&i.Body,
		&i.State,
	)
	return i, err
}

const getLastUpdateTime = `-- name: GetLastUpdateTime :one
SELECT github_id, github_updated_at
FROM issues
WHERE repository_id = ?
ORDER BY github_updated_at DESC
LIMIT 1
`

type GetLastUpdateTimeRow struct {
	GithubID        int64
	GithubUpdatedAt time.Time
}

func (q *Queries) GetLastUpdateTime(ctx context.Context, db DBTX, repositoryID int64) (GetLastUpdateTimeRow, error) {
	row := db.QueryRowContext(ctx, getLastUpdateTime, repositoryID)
	var i GetLastUpdateTimeRow
	err := row.Scan(&i.GithubID, &i.GithubUpdatedAt)
	return i, err
}

const listIssues = `-- name: ListIssues :many
SELECT id, repository_id, number, title, state
FROM issues
ORDER BY number DESC
`

type ListIssuesRow struct {
	ID           int64
	RepositoryID int64
	Number       int64
	Title        string
	State        string
}

func (q *Queries) ListIssues(ctx context.Context, db DBTX) ([]ListIssuesRow, error) {
	rows, err := db.QueryContext(ctx, listIssues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssuesRow{}
	for rows.Next() {
		var i ListIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Number,
			&i.Title,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertIssue = `-- name: UpsertIssue :exec
INSERT INTO issues (repository_id, github_id, number, title, body, state,
                    is_pull_request, pr_url, pr_html_url, pr_diff_url, pr_patch_url,
                    github_created_at, github_updated_at, synced_at)
VALUES (?, ?, ?, ?, ?, ?,
        ?, ?, ?, ?, ?,
        ?, ?, ?)
ON CONFLICT(github_id) DO UPDATE SET repository_id     = excluded.repository_id,
                                     title             = excluded.title,
                                     body              = excluded.body,
                                     state             = excluded.state,
                                     is_pull_request   = excluded.is_pull_request,
                                     pr_url            = excluded.pr_url,
                                     pr_html_url       = excluded.pr_html_url,
                                     pr_diff_url       = excluded.pr_diff_url,
                                     pr_patch_url      = excluded.pr_patch_url,
                                     github_created_at = excluded.github_created_at,
                                     github_updated_at = excluded.github_updated_at,
                                     updated_at        = datetime('now'),
                                     synced_at         = excluded.synced_at
`

type UpsertIssueParams struct {
	RepositoryID    int64
	GithubID        int64
	Number          int64
	Title           string
	Body            string
	State           string
	IsPullRequest   bool
	PrUrl           *string
	PrHtmlUrl       *string
	PrDiffUrl       *string
	PrPatchUrl      *string
	GithubCreatedAt time.Time
	GithubUpdatedAt time.Time
	SyncedAt        time.Time
}

func (q *Queries) UpsertIssue(ctx context.Context, db DBTX, arg UpsertIssueParams) error {
	_, err := db.ExecContext(ctx, upsertIssue,
		arg.RepositoryID,
		arg.GithubID,
		arg.Number,
		arg.Title,
		arg.Body,
		arg.State,
		arg.IsPullRequest,
		arg.PrUrl,
		arg.PrHtmlUrl,
		arg.PrDiffUrl,
		arg.PrPatchUrl,
		arg.GithubCreatedAt,
		arg.GithubUpdatedAt,
		arg.SyncedAt,
	)
	return err
}
