// Copyright 2026 thumbrise
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package sqlcgen

import (
	"context"
	"time"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (repository_id, issue_id, type, status, prompt, model)
VALUES (?, ?, ?, 'pending', ?, ?)
RETURNING id, created_at
`

type CreateJobParams struct {
	RepositoryID int64
	IssueID      int64
	Type         string
	Prompt       string
	Model        *string
}

type CreateJobRow struct {
	ID        int64
	CreatedAt time.Time
}

func (q *Queries) CreateJob(ctx context.Context, db DBTX, arg CreateJobParams) (CreateJobRow, error) {
	row := db.QueryRowContext(ctx, createJob,
		arg.RepositoryID,
		arg.IssueID,
		arg.Type,
		arg.Prompt,
		arg.Model,
	)
	var i CreateJobRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, created_at, updated_at, repository_id, issue_id,
       type, status, prompt, model, result, attempts, last_error
FROM jobs
WHERE id = ?
`

func (q *Queries) GetJobByID(ctx context.Context, db DBTX, id int64) (Job, error) {
	row := db.QueryRowContext(ctx, getJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RepositoryID,
		&i.IssueID,
		&i.Type,
		&i.Status,
		&i.Prompt,
		&i.Model,
		&i.Result,
		&i.Attempts,
		&i.LastError,
	)
	return i, err
}

const listDoneJobs = `-- name: ListDoneJobs :many
SELECT id, created_at, updated_at, repository_id, issue_id,
       type, status, prompt, model, result, attempts, last_error
FROM jobs
WHERE status = 'done'
ORDER BY updated_at ASC
LIMIT ?
`

func (q *Queries) ListDoneJobs(ctx context.Context, db DBTX, limit int64) ([]Job, error) {
	rows, err := db.QueryContext(ctx, listDoneJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RepositoryID,
			&i.IssueID,
			&i.Type,
			&i.Status,
			&i.Prompt,
			&i.Model,
			&i.Result,
			&i.Attempts,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByIssue = `-- name: ListJobsByIssue :many
SELECT id, created_at, updated_at, repository_id, issue_id,
       type, status, prompt, model, result, attempts, last_error
FROM jobs
WHERE issue_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListJobsByIssue(ctx context.Context, db DBTX, issueID int64) ([]Job, error) {
	rows, err := db.QueryContext(ctx, listJobsByIssue, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RepositoryID,
			&i.IssueID,
			&i.Type,
			&i.Status,
			&i.Prompt,
			&i.Model,
			&i.Result,
			&i.Attempts,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingJobs = `-- name: ListPendingJobs :many
SELECT id, created_at, updated_at, repository_id, issue_id,
       type, status, prompt, model, result, attempts, last_error
FROM jobs
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT ?
`

func (q *Queries) ListPendingJobs(ctx context.Context, db DBTX, limit int64) ([]Job, error) {
	rows, err := db.QueryContext(ctx, listPendingJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RepositoryID,
			&i.IssueID,
			&i.Type,
			&i.Status,
			&i.Prompt,
			&i.Model,
			&i.Result,
			&i.Attempts,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDone = `-- name: MarkDone :exec
UPDATE jobs
SET status     = 'done',
    result     = ?,
    updated_at = datetime('now')
WHERE id = ?
  AND status = 'processing'
`

type MarkDoneParams struct {
	Result *string
	ID     int64
}

func (q *Queries) MarkDone(ctx context.Context, db DBTX, arg MarkDoneParams) error {
	_, err := db.ExecContext(ctx, markDone, arg.Result, arg.ID)
	return err
}

const markFailed = `-- name: MarkFailed :exec
UPDATE jobs
SET status     = 'failed',
    last_error = ?,
    attempts   = attempts + 1,
    updated_at = datetime('now')
WHERE id = ?
  AND status = 'processing'
`

type MarkFailedParams struct {
	LastError *string
	ID        int64
}

func (q *Queries) MarkFailed(ctx context.Context, db DBTX, arg MarkFailedParams) error {
	_, err := db.ExecContext(ctx, markFailed, arg.LastError, arg.ID)
	return err
}

const markProcessing = `-- name: MarkProcessing :exec
UPDATE jobs
SET status     = 'processing',
    updated_at = datetime('now')
WHERE id = ?
  AND status = 'pending'
`

func (q *Queries) MarkProcessing(ctx context.Context, db DBTX, id int64) error {
	_, err := db.ExecContext(ctx, markProcessing, id)
	return err
}

const retryFailedJobs = `-- name: RetryFailedJobs :exec
UPDATE jobs
SET status     = 'pending',
    updated_at = datetime('now')
WHERE status = 'failed'
  AND attempts < ?
`

func (q *Queries) RetryFailedJobs(ctx context.Context, db DBTX, attempts int64) error {
	_, err := db.ExecContext(ctx, retryFailedJobs, attempts)
	return err
}
