// Copyright 2026 thumbrise
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"time"
)

type Comment struct {
	ID              int64
	CreatedAt       *time.Time
	UpdatedAt       *time.Time
	IssueID         int64
	GithubID        int64
	Body            *string
	AuthorLogin     *string
	AuthorGithubID  *int64
	GithubCreatedAt time.Time
	GithubUpdatedAt time.Time
}

type Issue struct {
	ID              int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
	RepositoryID    int64
	GithubID        int64
	Number          int64
	Title           string
	Body            string
	State           string
	IsPullRequest   bool
	PrUrl           *string
	PrHtmlUrl       *string
	PrDiffUrl       *string
	PrPatchUrl      *string
	GithubCreatedAt time.Time
	GithubUpdatedAt time.Time
	SyncedAt        time.Time
}

type IssueAssignee struct {
	IssueID int64
	UserID  int64
}

type IssueLabel struct {
	IssueID int64
	LabelID int64
}

type Label struct {
	ID           int64
	CreatedAt    *time.Time
	UpdatedAt    *time.Time
	RepositoryID int64
	GithubID     int64
	Name         string
	Color        *string
	Description  *string
}

type Repository struct {
	ID        int64
	CreatedAt *time.Time
	UpdatedAt *time.Time
	Owner     string
	Name      string
	Enabled   *bool
	LastError *string
}

type SyncCursor struct {
	ID             int64
	CreatedAt      *time.Time
	UpdatedAt      *time.Time
	RepositoryID   int64
	ResourceType   string
	SinceUpdatedAt *time.Time
	NextPage       *int64
	ETag           *string
}

type User struct {
	ID        int64
	CreatedAt *time.Time
	UpdatedAt *time.Time
	GithubID  int64
	Login     string
}
