// Copyright 2026 thumbrise
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package sqlcgen

import (
	"context"
	"time"
)

const ackOutboxEvent = `-- name: AckOutboxEvent :exec
UPDATE outbox_events
SET processed_at = datetime('now')
WHERE id = ? AND processed_at IS NULL
`

func (q *Queries) AckOutboxEvent(ctx context.Context, db DBTX, id int64) error {
	_, err := db.ExecContext(ctx, ackOutboxEvent, id)
	return err
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox_events (topic, resource_id, repository_id)
VALUES (?, ?, ?)
`

type InsertOutboxEventParams struct {
	Topic        string
	ResourceID   int64
	RepositoryID int64
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, db DBTX, arg InsertOutboxEventParams) error {
	_, err := db.ExecContext(ctx, insertOutboxEvent, arg.Topic, arg.ResourceID, arg.RepositoryID)
	return err
}

const pendingOutboxEvents = `-- name: PendingOutboxEvents :many
SELECT id, created_at, topic, resource_id, repository_id
FROM outbox_events
WHERE topic = ? AND processed_at IS NULL
ORDER BY created_at ASC
LIMIT ?
`

type PendingOutboxEventsParams struct {
	Topic string
	Limit int64
}

type PendingOutboxEventsRow struct {
	ID           int64
	CreatedAt    time.Time
	Topic        string
	ResourceID   int64
	RepositoryID int64
}

func (q *Queries) PendingOutboxEvents(ctx context.Context, db DBTX, arg PendingOutboxEventsParams) ([]PendingOutboxEventsRow, error) {
	rows, err := db.QueryContext(ctx, pendingOutboxEvents, arg.Topic, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingOutboxEventsRow{}
	for rows.Next() {
		var i PendingOutboxEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Topic,
			&i.ResourceID,
			&i.RepositoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
