// Copyright 2026 thumbrise
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repositories.sql

package sqlcgen

import (
	"context"
)

const getByOwnerName = `-- name: GetByOwnerName :one
SELECT id
FROM repositories
WHERE owner = ? AND name = ?
`

type GetByOwnerNameParams struct {
	Owner string
	Name  string
}

func (q *Queries) GetByOwnerName(ctx context.Context, db DBTX, arg GetByOwnerNameParams) (int64, error) {
	row := db.QueryRowContext(ctx, getByOwnerName, arg.Owner, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertRepository = `-- name: UpsertRepository :one
INSERT INTO repositories (owner, name, created_at, updated_at)
VALUES (?, ?, datetime('now'), datetime('now'))
ON CONFLICT(owner, name) DO UPDATE SET updated_at = datetime('now')
RETURNING id
`

type UpsertRepositoryParams struct {
	Owner string
	Name  string
}

func (q *Queries) UpsertRepository(ctx context.Context, db DBTX, arg UpsertRepositoryParams) (int64, error) {
	row := db.QueryRowContext(ctx, upsertRepository, arg.Owner, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}
