// Copyright 2026 thumbrise
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync_cursors.sql

package sqlcgen

import (
	"context"
	"time"
)

const getSyncCursor = `-- name: GetSyncCursor :one
SELECT id, created_at, updated_at, repository_id, resource_type, since_updated_at, next_page, e_tag
FROM sync_cursors
WHERE repository_id = ? AND resource_type = ?
`

type GetSyncCursorParams struct {
	RepositoryID int64
	ResourceType string
}

func (q *Queries) GetSyncCursor(ctx context.Context, db DBTX, arg GetSyncCursorParams) (SyncCursor, error) {
	row := db.QueryRowContext(ctx, getSyncCursor, arg.RepositoryID, arg.ResourceType)
	var i SyncCursor
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RepositoryID,
		&i.ResourceType,
		&i.SinceUpdatedAt,
		&i.NextPage,
		&i.ETag,
	)
	return i, err
}

const upsertSyncCursor = `-- name: UpsertSyncCursor :exec
INSERT INTO sync_cursors (repository_id, resource_type, since_updated_at, next_page, e_tag, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, datetime('now'), datetime('now'))
ON CONFLICT (repository_id, resource_type)
DO UPDATE SET since_updated_at = excluded.since_updated_at,
              next_page        = excluded.next_page,
              e_tag            = excluded.e_tag,
              updated_at       = datetime('now')
`

type UpsertSyncCursorParams struct {
	RepositoryID   int64
	ResourceType   string
	SinceUpdatedAt time.Time
	NextPage       int64
	ETag           string
}

func (q *Queries) UpsertSyncCursor(ctx context.Context, db DBTX, arg UpsertSyncCursorParams) error {
	_, err := db.ExecContext(ctx, upsertSyncCursor,
		arg.RepositoryID,
		arg.ResourceType,
		arg.SinceUpdatedAt,
		arg.NextPage,
		arg.ETag,
	)
	return err
}
